//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyGridHelpersTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PropertyGridHelpersTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- None --.
        /// </summary>
        internal static string Blank_Entry {
            get {
                return ResourceManager.GetString("Blank_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Category.
        /// </summary>
        internal static string Category_TestCategory {
            get {
                return ResourceManager.GetString("Category_TestCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Description.
        /// </summary>
        internal static string Description_TestDescription {
            get {
                return ResourceManager.GetString("Description_TestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Display Name.
        /// </summary>
        internal static string DisplayName_TestDisplayName {
            get {
                return ResourceManager.GetString("DisplayName_TestDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor Edit Style is set as expected.  It is set to DropDown..
        /// </summary>
        internal static string EditorStyle {
            get {
                return ResourceManager.GetString("EditorStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditValue returned null as expected.
        /// </summary>
        internal static string EditValueNull {
            get {
                return ResourceManager.GetString("EditValueNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NullValueString {
            get {
                return ResourceManager.GetString("NullValueString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars Test Text.
        /// </summary>
        internal static string Stars {
            get {
                return ResourceManager.GetString("Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Category.
        /// </summary>
        internal static string Test_Category {
            get {
                return ResourceManager.GetString("Test_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Item.
        /// </summary>
        internal static string Test_Item {
            get {
                return ResourceManager.GetString("Test_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalizedValue.
        /// </summary>
        internal static string TestKey {
            get {
                return ResourceManager.GetString("TestKey", resourceCulture);
            }
        }
    }
}
