name: Update GitHub Pages on Dispatch

on:
  repository_dispatch:
    types:
      - update-gh-pages

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the main repository
      uses: actions/checkout@v3

    - name: Clone the CodeCoverage repository
      run: |
        git clone https://${{ secrets.PAT_TOKEN }}@github.com/dparvin/PropertyGridHelpers.CodeCoverage.git codecoverage-repo

    - name: List files in codecoverage-repo
      run: ls -R codecoverage-repo

    - name: Copy coverage files to gh-pages
      run: |
        mkdir -p gh-pages
        cp -a codecoverage-repo/pages/* gh-pages/

    - name: List files in gh-pages
      run: ls -R gh-pages

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: gh-pages
        force_orphan: true  # Ensures a clean gh-pages branch
